[project]
name = "alibabacloud-rds-openapi-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alibabacloud-rds20140815>=11.0.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
